set :deploy_to, deploysecret(:deploy_to)
set :server, deploysecret(:server)
set :server_name, deploysecret(:server_name)
set :db_server, deploysecret(:db_server)
set :db_user, deploysecret(:db_user)
set :db_password, deploysecret(:db_password)
set :branch, deploysecret(:branch)
set :ssh_options, port: deploysecret(:port)
set :stage, deploysecret(:stage)
set :rails_env, deploysecret(:rails_env)
set :enable_ssl, deploysecret(:enable_ssl)
server fetch(:server_name), user: fetch(:deploy_user), roles: %w(web app db importer)
